version: "3"
services:
  httpd-static:
    image: annenmrts/httpd
    container_name: httpd-static
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 8080:80
    labels:
      - traefik.http.routers.httpd-static.rule=Host(`localhost`)
  express:
    image: annenmrts/express
    container_name: express-server
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 8081:1337
    labels:
      - traefik.http.routers.express-server.rule=PathPrefix(`/api`)
      - traefik.http.routers.express-server.middlewares=admin-stripprefix
      - traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/api
  reverse_proxy:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8001:8080
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    name: traefik-net